project:
  type: website

execute:
  echo: false
  warning: false
  message: false

website:
  title: "R for the Rest of Us Handbook"
  search: false
 

  sidebar:
    style: "floating"
    search: true
    border: true
    logo: assets/rru-logo-text-right-stacked.png
    
    contents:
      - index.qmd
      - section: "Operations"
        contents:
        - david-responsibilities.qmd
        - tools.qmd
        - communication.qmd
        - finances.qmd
        - contracts.qmd
        - clients.qmd
      - section: "Marketing"
        contents:
        - marketing-overview.qmd
        - branding.qmd
        - website.qmd
        - content-strategy.qmd
        - email-automations.qmd
        - social-media.qmd
      - section: "Course Manual"
        contents: 
        - course-manual.qmd
      - section: "Consulting"
        contents:
        - project-management.qmd

format:
  html:
    toc: true
    toc-depth: 4
    theme: litera
    css: styles.css



