on:
  push:
    branches: main

name: Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: rocker/verse:4.3.0
    steps:
      - name: Install dependencies
        run: |
         install.packages("remotes")
         remotes::install_github("rfortherestofus/rfortherestofus")
        shell: Rscript {0}

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Render and Publish to Netlify
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}